/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Main.WorkSpaceProfiles.OrderManagement;

import TheBusiness.Business.Business;
import TheBusiness.CustomerManagement.CustomerProfile;
import TheBusiness.SalesManagement.SalesPersonProfile;
import UserInterface.ManageTheBusiness.AllSolutionOrdersJPanel;
import UserInterface.ManageTheBusiness.B2BsolutionOrdersJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author thivya
 */
public class ManageSalesPersonOrdersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessOrderJPanel
     */
    Business business;
    SalesPersonProfile salesperson;
    JPanel CardSequencePanel;
    CustomerProfile selectedcustomer;
    public ManageSalesPersonOrdersJPanel(Business business, JPanel CardSequencePanel) {
        initComponents();
        this.business=business;
        this.CardSequencePanel=CardSequencePanel;
        this.salesperson=salesperson;
        this.selectedcustomer=selectedcustomer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        btnNormalOrder = new javax.swing.JButton();
        btnSolutionOrder = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 153, 153));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        leftPanel.setBackground(new java.awt.Color(0, 153, 153));

        btnNormalOrder.setText("Normal Order Sales");
        btnNormalOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormalOrderActionPerformed(evt);
            }
        });

        btnSolutionOrder.setText("Solution Order Sales");
        btnSolutionOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolutionOrderActionPerformed(evt);
            }
        });

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Back)
                .addGap(52, 52, 52)
                .addComponent(btnNormalOrder)
                .addGap(61, 61, 61)
                .addComponent(btnSolutionOrder)
                .addContainerGap(416, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNormalOrder)
                    .addComponent(btnSolutionOrder)
                    .addComponent(Back))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(leftPanel);

        userProcessContainer.setBackground(new java.awt.Color(0, 153, 153));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolutionOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolutionOrderActionPerformed
        // TODO add your handling code here:
        AllSolutionOrdersJPanel allSolutionOrdersJPanel = new AllSolutionOrdersJPanel(business, userProcessContainer);
       this.userProcessContainer.add("allSolutionOrdersJPanel",allSolutionOrdersJPanel);
        ((CardLayout)this.userProcessContainer.getLayout()).next(this.userProcessContainer);
    }//GEN-LAST:event_btnSolutionOrderActionPerformed

    private void btnNormalOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalOrderActionPerformed
        // TODO add your handling code here:
        ManageSalesPersonOrders manageSalesPersonOrders = new ManageSalesPersonOrders(business, leftPanel);
        this.userProcessContainer.add("manageSalesPersonOrders",manageSalesPersonOrders);
        ((CardLayout)this.userProcessContainer.getLayout()).next(this.userProcessContainer);
    }//GEN-LAST:event_btnNormalOrderActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnNormalOrder;
    private javax.swing.JButton btnSolutionOrder;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
