/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.ManageTheBusiness;

import TheBusiness.Business.Business;
import TheBusiness.MarketModel.MarketChannelAssignment;
import TheBusiness.MarketModel.MarketChannelComboCatalog;
import TheBusiness.MarketModel.SolutionOffer;
import TheBusiness.ProductManagement.Product;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sathya
 */
public class AllSolutionsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AllSolutionsJPanel
     */
     JPanel userProcessContainer;
     Business business;
     MarketChannelAssignment mca;
     MarketChannelComboCatalog mccc;
    
    public AllSolutionsJPanel(Business business, JPanel userProcessContainer) {
        initComponents();
        this.business = business;
        this.userProcessContainer = userProcessContainer;
        this.mccc = this.business.getMarketChannelComboCatalog();
        populateMarketChannelComboBox();
        this.mca=(MarketChannelAssignment)this.MarketChannelComboBox.getSelectedItem();
        refreshSolutionBundleTbl(mca);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MarketChannelComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        solutionBundleTbl = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Product Bundle Solutions");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 16, -1, 28));

        MarketChannelComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MarketChannelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarketChannelComboBoxActionPerformed(evt);
            }
        });
        add(MarketChannelComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 94, 150, -1));

        jLabel2.setText("Market Channel");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 72, 114, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 21, 90, -1));

        solutionBundleTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Products", "Price"
            }
        ));
        jScrollPane3.setViewportView(solutionBundleTbl);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 576, 110));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Solutions");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 68, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void MarketChannelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarketChannelComboBoxActionPerformed
        // TODO add your handling code here:
        this.mca = (MarketChannelAssignment)this.MarketChannelComboBox.getSelectedItem();
        refreshSolutionBundleTbl(mca);
    }//GEN-LAST:event_MarketChannelComboBoxActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox MarketChannelComboBox;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable solutionBundleTbl;
    // End of variables declaration//GEN-END:variables

    private void populateMarketChannelComboBox() {
        this.MarketChannelComboBox.removeAllItems();
        for(MarketChannelAssignment mca : this.mccc.getMcalist())
            this.MarketChannelComboBox.addItem(mca);     
    }    

    private void refreshSolutionBundleTbl(MarketChannelAssignment mca) {
       DefaultTableModel dtm = (DefaultTableModel)solutionBundleTbl.getModel();
       dtm.setRowCount(0);
       if(mca==null){
           return;
       }
       else{
           for(SolutionOffer solutionOffer : this.mca.getSolutionofferlist()){
           Object[] obj = new Object[2];
           obj[0] = solutionOffer;
           obj[1] = solutionOffer.getSolutionPrice();
           dtm.addRow(obj);
          }                   
        }

     
    }
}
