/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.ManageTheBusiness;

import TheBusiness.Business.Business;
import TheBusiness.CustomerManagement.CustomerProfile;
import TheBusiness.SolutionOrders.SolutionOrder;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sathya
 */
public class AllSolutionOrdersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AllSolutionOrdersJPanel
     */
    Business business;
    JPanel userProcessContainer;
    
    public AllSolutionOrdersJPanel(Business business, JPanel userProcessContainer) {
        initComponents();
        this.business = business;
        this.userProcessContainer = userProcessContainer;
        populateCustomerCmbBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        customerCmbBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        solutionOrdersTbl = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        netPurchaseTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Solution Orders");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 18, 119, 28));

        customerCmbBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        customerCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerCmbBoxActionPerformed(evt);
            }
        });
        add(customerCmbBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 92, 150, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Customer");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 64, 58, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 23, 90, -1));

        solutionOrdersTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Solutions", "Price"
            }
        ));
        jScrollPane3.setViewportView(solutionOrdersTbl);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 162, 576, 110));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Solutions");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 132, 68, -1));

        netPurchaseTextField.setEditable(false);
        add(netPurchaseTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 291, 101, -1));

        jLabel3.setText("Customer Net Purchase Amount");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 290, 184, 24));
    }// </editor-fold>//GEN-END:initComponents

    private void customerCmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerCmbBoxActionPerformed
        // TODO add your handling code here:
        if((CustomerProfile)this.customerCmbBox.getSelectedItem()!=null)
        populateSolutionOrdersTbl((CustomerProfile)this.customerCmbBox.getSelectedItem());
         
    }//GEN-LAST:event_customerCmbBoxActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox customerCmbBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField netPurchaseTextField;
    private javax.swing.JTable solutionOrdersTbl;
    // End of variables declaration//GEN-END:variables

    private void populateCustomerCmbBox() {
        this.customerCmbBox.removeAllItems();
        for(CustomerProfile customerProfile : this.business.getCustomerDirectory().getCustomerlist()){
            this.customerCmbBox.addItem(customerProfile);
        }
    }

    private void populateSolutionOrdersTbl(CustomerProfile customerProfile) {
        float net_purchase=0;
        DefaultTableModel dtm = (DefaultTableModel)this.solutionOrdersTbl.getModel();
        dtm.setRowCount(0);
        for(SolutionOrder solutionOrder :this.business.getMasterSolutionOrderList().getSolutionorderlist()){
            if(solutionOrder.getCustomerprofile().equals(customerProfile)){
                Object[] obj = new Object[2];
                obj[0] = solutionOrder.getSelectedsolutionoffer();
                obj[1] = solutionOrder.getSolutionPrice();
                dtm.addRow(obj);
                net_purchase+=solutionOrder.getSolutionPrice();
            }
        }
        netPurchaseTextField.setText(String.valueOf(net_purchase));
         
    }
}
