/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.ManageTheBusiness;

import TheBusiness.Personnel.Person;


/**
 *
 * @author anushasenthilnathan
 */
import TheBusiness.Business.Business;
import TheBusiness.ProductManagement.Product;
import TheBusiness.Supplier.Supplier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
public class ManagePriceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePriceJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    Supplier selectedsupplier;
    Product selectedproduct;
    
    public ManagePriceJPanel(Business bz, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        populateTable();
        populateProduct();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        priceTable = new javax.swing.JTable();
        cmbSupplier = new javax.swing.JComboBox();
        lblSupplier = new javax.swing.JLabel();
        btnEditProductDetails = new javax.swing.JButton();

        priceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product", "Floor", "Ceiling", "Target"
            }
        ));
        jScrollPane1.setViewportView(priceTable);

        cmbSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSupplierActionPerformed(evt);
            }
        });

        lblSupplier.setText("Supplier:");

        btnEditProductDetails.setText("Edit Product Details");
        btnEditProductDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProductDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditProductDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(lblSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditProductDetails)
                .addGap(205, 205, 205))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSupplierActionPerformed
        // TODO add your handling code here:
        //populateProductTable();
        populateProduct();
    }//GEN-LAST:event_cmbSupplierActionPerformed

    private void btnEditProductDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProductDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = priceTable.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select the product first.");
            return;
        }
       Product product = (Product) priceTable.getValueAt(selectedRowIndex, 0);
////        Supplier supplier = (Supplier) cmbSupplier.getSelectedItem();
//        ViewProductDetailJPanel1 vpj = new ViewProductDetailJPanel1(business,CardSequencePanel, product);
//        CardSequencePanel.add("ViewProductDetailJPanel1", vpj);
//        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


 CardSequencePanel.removeAll();

        ViewProductDetailJPanel viewProductDetailJPanel = new ViewProductDetailJPanel(business,CardSequencePanel, product);

        CardSequencePanel.add("ViewProductDetailJPanel", viewProductDetailJPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnEditProductDetailsActionPerformed

    private void populateTable() {
        cmbSupplier.removeAllItems();
        for (Supplier supplier : business.getSupplierDirectory().getSupplierList()) {
            cmbSupplier.addItem(supplier);
        }
        
    }
    
    private void populateProduct() {
        Supplier selectedSupplier = (Supplier) cmbSupplier.getSelectedItem();
        if (selectedSupplier == null) {
            return;
        }
        DefaultTableModel model = (DefaultTableModel) priceTable.getModel();
        model.setRowCount(0);
        
        for(Product p : selectedSupplier.getProductCatalog().getProductList()){
            Object row[] = new Object[4];
            row[0] = p.getName();
            row[1] = p.getFloorPrice();
            row[2] = p.getCeilingPrice();
            row[3] = p.getTargetPrice();
            model.addRow(row);
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditProductDetails;
    private javax.swing.JComboBox cmbSupplier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JTable priceTable;
    // End of variables declaration//GEN-END:variables
}
