/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.ManageTheBusiness;

import TheBusiness.Business.Business;
import TheBusiness.MarketModel.Channel;
import TheBusiness.MarketModel.Market;
import TheBusiness.MarketModel.MarketChannelAssignment;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author thivya
 */
public class ManageChannelMarketJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageChannelMarketJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    public ManageChannelMarketJPanel(Business business, JPanel CardSequencePanel) {
        initComponents();
        this.CardSequencePanel = CardSequencePanel;
        this.business = business;
        
        cmbChannel.removeAllItems();
        cmbMarket.removeAllItems();
         
        for(Channel channel : business.getChannelCatalog().getChannellist()){
            cmbChannel.addItem(channel);
            
        }
        for(Market market : business.getMarketCatalog().getMarkets()){
            cmbMarket.addItem(market);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageChannel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        cmbMarket = new javax.swing.JComboBox();
        cmbChannel = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(0, 153, 153));

        lblManageChannel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblManageChannel.setText("MarketChannel Assignment");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Name of the Channel");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Market");

        btnAdd.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        cmbMarket.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        cmbMarket.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMarketActionPerformed(evt);
            }
        });

        cmbChannel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        cmbChannel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbChannel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbChannelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbChannel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(btnAdd)))
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblManageChannel)
                .addGap(185, 185, 185))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblManageChannel)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbChannel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnAdd)
                .addContainerGap(296, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMarketActionPerformed

    }//GEN-LAST:event_cmbMarketActionPerformed

    private void cmbChannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbChannelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbChannelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Channel channel = (Channel) cmbChannel.getSelectedItem();
        Market market = (Market) cmbMarket.getSelectedItem();
        MarketChannelAssignment mcc= business.getMarketChannelComboCatalog().newMarketChannelCombo(market, channel);
        
        if(mcc==null){
           JOptionPane.showMessageDialog(this, "MarketChannelAssignment already exists for the specified Market and Channel.","ERROR", JOptionPane.ERROR_MESSAGE);

        }else
            JOptionPane.showMessageDialog(this, "MarketChannelAssignment added successfully");

    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox cmbChannel;
    private javax.swing.JComboBox cmbMarket;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblManageChannel;
    // End of variables declaration//GEN-END:variables
}
